Backoffice/beaches_control_manager/config/routes.rb
Rails.application.routes.draw do

  resources :beaches
  resources :users

  get '/index', :to => static('index.html')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Backoffice/beaches_control_manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Backoffice/beaches_control_manager/app/models/beach.rb
class Beach < ApplicationRecord
end

Backoffice/beaches_control_manager/app/models/user.rb
class User < ApplicationRecord
end

Backoffice/beaches_control_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Backoffice/beaches_control_manager/app/controllers/beaches_controller.rb
class BeachesController < ApplicationController
  before_action :set_beach, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /beaches
  # GET /beaches.json
  def index
    @beaches = Beach.all
  end

  # GET /beaches/1
  # GET /beaches/1.json
  def show
  end

  # GET /beaches/new
  def new
    @beach = Beach.new
  end

  # GET /beaches/1/edit
  def edit
  end

  # POST /beaches
  # POST /beaches.json
  def create
    @beach = Beach.new(beach_params)

    respond_to do |format|
      if @beach.save
        format.html { redirect_to @beach, notice: 'Beach was successfully created.' }
        format.json { render :show, status: :created, location: @beach }
      else
        format.html { render :new }
        format.json { render json: @beach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beaches/1
  # PATCH/PUT /beaches/1.json
  def update
    respond_to do |format|
      if @beach.update(beach_params)
        format.html { redirect_to @beach, notice: 'Beach was successfully updated.' }
        format.json { render :show, status: :ok, location: @beach }
      else
        format.html { render :edit }
        format.json { render json: @beach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beaches/1
  # DELETE /beaches/1.json
  def destroy
    @beach.destroy
    respond_to do |format|
      format.html { redirect_to beaches_url, notice: 'Beach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beach
      @beach = Beach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beach_params
      params.permit(:beach_name, :location, :sand_color, :description, :main_image, :secondary_image, :latitude, :longitude, :wave_type, :snorkeling, :swimming, :shade, :night_life, :camping_zone, :protected_area, :cristal_water, :vegetation, :comments)
      #Así estaba
      #params.require(:beach).permit(:beach_name, :location, :sand_color, :description, :main_image, :secondary_image, :latitude, :longitude, :wave_type, :snorkeling, :swimming, :shade, :night_life, :camping_zone, :protected_area, :cristal_water, :vegetation, :comments)
    end
end

Backoffice/beaches_control_manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  #Probar metodo POST con el comando anterior

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #Asi permite hacer request pero no funcionan los forms generado por Rails scaffold
      params.permit(:name, :last_name, :nationality, :profile_picture, :phone_number, :email, :password, :location)
      
      #Así estaba por default, pero no permite agregar hacer Request desde JSON
      #params.require(:user).permit(:name, :last_name, :nationality, :profile_picture, :phone_number, :email, :password, :location)
    end
end

Backoffice/beaches_control_manager/app/helpers/application_helper.rb
module ApplicationHelper
end

Backoffice/beaches_control_manager/app/helpers/beaches_helper.rb
module BeachesHelper
end

Backoffice/beaches_control_manager/app/helpers/users_helper.rb
module UsersHelper
end

Backoffice/beaches_control_manager/app/views/beaches/_form.html.erb
<%= form_for(beach) do |f| %>
  <% if beach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beach.errors.count, "error") %> prohibited this beach from being saved:</h2>

      <ul>
      <% beach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beach_name %>
    <%= f.text_field :beach_name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :sand_color %>
    <%= f.text_field :sand_color %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :main_image %>
    <%= f.text_field :main_image %>
  </div>

  <div class="field">
    <%= f.label :secondary_image %>
    <%= f.text_field :secondary_image %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :wave_type %>
    <%= f.text_field :wave_type %>
  </div>

  <div class="field">
    <%= f.label :snorkeling %>
    <%= f.check_box :snorkeling %>
  </div>

  <div class="field">
    <%= f.label :swimming %>
    <%= f.check_box :swimming %>
  </div>

  <div class="field">
    <%= f.label :shade %>
    <%= f.check_box :shade %>
  </div>

  <div class="field">
    <%= f.label :night_life %>
    <%= f.check_box :night_life %>
  </div>

  <div class="field">
    <%= f.label :camping_zone %>
    <%= f.check_box :camping_zone %>
  </div>

  <div class="field">
    <%= f.label :protected_area %>
    <%= f.check_box :protected_area %>
  </div>

  <div class="field">
    <%= f.label :cristal_water %>
    <%= f.check_box :cristal_water %>
  </div>

  <div class="field">
    <%= f.label :vegetation %>
    <%= f.text_field :vegetation %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_field :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Backoffice/beaches_control_manager/app/views/beaches/edit.html.erb
<h1>Editing Beach</h1>

<%= render 'form', beach: @beach %>

<%= link_to 'Show', @beach %> |
<%= link_to 'Back', beaches_path %>

Backoffice/beaches_control_manager/app/views/beaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beaches</h1>

<table>
  <thead>
    <tr>
      <th>Beach name</th>
      <th>Location</th>
      <th>Sand color</th>
      <th>Description</th>
      <th>Main image</th>
      <th>Secondary image</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Wave type</th>
      <th>Snorkeling</th>
      <th>Swimming</th>
      <th>Shade</th>
      <th>Night life</th>
      <th>Camping zone</th>
      <th>Protected area</th>
      <th>Cristal water</th>
      <th>Vegetation</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beaches.each do |beach| %>
      <tr>
        <td><%= beach.beach_name %></td>
        <td><%= beach.location %></td>
        <td><%= beach.sand_color %></td>
        <td><%= beach.description %></td>
        <td><%= beach.main_image %></td>
        <td><%= beach.secondary_image %></td>
        <td><%= beach.latitude %></td>
        <td><%= beach.longitude %></td>
        <td><%= beach.wave_type %></td>
        <td><%= beach.snorkeling %></td>
        <td><%= beach.swimming %></td>
        <td><%= beach.shade %></td>
        <td><%= beach.night_life %></td>
        <td><%= beach.camping_zone %></td>
        <td><%= beach.protected_area %></td>
        <td><%= beach.cristal_water %></td>
        <td><%= beach.vegetation %></td>
        <td><%= beach.comments %></td>
        <td><%= link_to 'Show', beach %></td>
        <td><%= link_to 'Edit', edit_beach_path(beach) %></td>
        <td><%= link_to 'Destroy', beach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beach', new_beach_path %>

Backoffice/beaches_control_manager/app/views/beaches/new.html.erb
<h1>New Beach</h1>

<%= render 'form', beach: @beach %>

<%= link_to 'Back', beaches_path %>

Backoffice/beaches_control_manager/app/views/beaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beach name:</strong>
  <%= @beach.beach_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @beach.location %>
</p>

<p>
  <strong>Sand color:</strong>
  <%= @beach.sand_color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beach.description %>
</p>

<p>
  <strong>Main image:</strong>
  <%= @beach.main_image %>
</p>

<p>
  <strong>Secondary image:</strong>
  <%= @beach.secondary_image %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @beach.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @beach.longitude %>
</p>

<p>
  <strong>Wave type:</strong>
  <%= @beach.wave_type %>
</p>

<p>
  <strong>Snorkeling:</strong>
  <%= @beach.snorkeling %>
</p>

<p>
  <strong>Swimming:</strong>
  <%= @beach.swimming %>
</p>

<p>
  <strong>Shade:</strong>
  <%= @beach.shade %>
</p>

<p>
  <strong>Night life:</strong>
  <%= @beach.night_life %>
</p>

<p>
  <strong>Camping zone:</strong>
  <%= @beach.camping_zone %>
</p>

<p>
  <strong>Protected area:</strong>
  <%= @beach.protected_area %>
</p>

<p>
  <strong>Cristal water:</strong>
  <%= @beach.cristal_water %>
</p>

<p>
  <strong>Vegetation:</strong>
  <%= @beach.vegetation %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @beach.comments %>
</p>

<%= link_to 'Edit', edit_beach_path(@beach) %> |
<%= link_to 'Back', beaches_path %>

Backoffice/beaches_control_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeachesControlManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Backoffice/beaches_control_manager/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </div>

  <div class="field">
    <%= f.label :profile_picture %>
    <%= f.text_field :profile_picture %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_area :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Backoffice/beaches_control_manager/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Backoffice/beaches_control_manager/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Nationality</th>
      <th>Profile picture</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Password</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.nationality %></td>
        <td><%= user.profile_picture %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Backoffice/beaches_control_manager/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Backoffice/beaches_control_manager/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @user.nationality %>
</p>

<p>
  <strong>Profile picture:</strong>
  <%= @user.profile_picture %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>